version = "3.7.15" # Must match or be close to your plugin's internal version
runner.dialect = scala212 # Change to scala213 or scala3 depending on your project

maxColumn = 100
assumeStandardLibraryStripMargin = true
align.preset = more # Options: none, some, more (aligns tokens like `=>`, `%%`, etc.)